
enum character {
    lowercaseLetter,
    number,
    upperCaseLetter,
    underscore,
    equals,
    lessThan,
    greaterThan,
    bang,
    colon,
    leftParen,
    rightParen,
    leftBracket,
    rightBracket,
    leftCurlyBracket,
    rightCurlyBracket,
    comma,
    dot,
    add,
    subtract,
    multiply,
    divide,
    mod,
    semiColon,
    whiteSpace,
    illegalCharacter,
};